# kitty configuration

font_family      ProggyCleanSZ Nerd Font
font_size        20.0

# scrollback
scrollback_lines 10000

# tabs
tab_bar_edge     bottom
tab_bar_style    powerline

# bell
enable_audio_bell no


# BEGIN_KITTY_THEME
# zenwritten_dark
include current-theme.conf
# END_KITTY_THEME
